name: fine
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter:
  line_icons: ^2.0.1
  flutter_swiper : ^1.1.6
  google_fonts: ^4.0.3
  flutter_svg: ^0.22.0
  cached_network_image: ^3.1.0
  curved_navigation_bar: ^1.0.3
  badges: ^2.0.2
  carousel_slider: ^4.0.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.1.0
  flutter_signin_button: ^2.0.0
  multiavatar: ^0.1.5
  material_design_icons_flutter: ^5.0.6595
  shared_preferences: ^2.0.6
  provider: ^6.0.3
  get: ^4.1.4
  dio: ^4.0.0
  firebase_messaging: ^14.2.1
  scoped_model: ^2.0.0-nullsafety.0
  firebase_analytics: ^10.0.6
  firebase_dynamic_links: ^5.0.11
  introduction_screen: ^2.1.0
  flutter_icons: ^1.1.0
  intl: ^0.17.0
  reactive_forms: ^10.7.0
  shimmer: ^2.0.0
  flutter_neumorphic: ^3.2.0
  smooth_page_indicator: ^1.0.1
  logger: ^1.2.2
  scroll_to_index: ^3.0.1
  collection: ^1.17.0
  # url_launcher: ^6.1.10

dependency_overrides:
  firebase_auth_platform_interface: 6.11.7
  firebase_messaging_platform_interface: 4.2.10
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/icons/
  - assets/icons/category/
  - assets/images/

  fonts:
    - family: Fira Sans
      fonts:
        - asset: assets/fonts/FiraSans-Black.ttf
        - asset: assets/fonts/FiraSans-BlackItalic.ttf
        - asset: assets/fonts/FiraSans-Bold.ttf
        - asset: assets/fonts/FiraSans-BoldItalic.ttf
        - asset: assets/fonts/FiraSans-ExtraBold.ttf
        - asset: assets/fonts/FiraSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/FiraSans-ExtraLight.ttf
        - asset: assets/fonts/FiraSans-ExtraLightItalic.ttf
        - asset: assets/fonts/FiraSans-Italic.ttf
        - asset: assets/fonts/FiraSans-Light.ttf
        - asset: assets/fonts/FiraSans-LightItalic.ttf
        - asset: assets/fonts/FiraSans-Medium.ttf
        - asset: assets/fonts/FiraSans-MediumItalic.ttf
        - asset: assets/fonts/FiraSans-Regular.ttf
        - asset: assets/fonts/FiraSans-SemiBold.ttf
        - asset: assets/fonts/FiraSans-SemiBoldItalic.ttf
        - asset: assets/fonts/FiraSans-Thin.ttf
        - asset: assets/fonts/FiraSans-ThinItalic.ttf





